const S=[["eia", "Байгаль орчны нөлөөллийн нарийвчилсан үнэлгээ (БОННҮ)", "Detailed Environmental Impact Assessment (DEIA)"], ["emp", "Байгаль орчны менежментийн төлөвлөгөө (БОМТ)", "Environmental Management Plan (EMP)"], ["mon", "Хяналт шинжилгээ, аудит", "Monitoring and audit"], ["gen", "Байгаль орчны хохирлын үнэлгээ", "Environmental damage assessment"], ["bio", "Ургамал, амьтны судалгаа", "Flora and fauna surveys"], ["rec", "Нөхөн сэргээлт", "Land rehabilitation"], ["adv", "Зөвлөх үйлчилгээ, сургалт", "Advisory and training"]];
const N=[['index.html','Нүүр','Home'],['about.html','Бидний тухай','About us'],['services.html','Үйлчилгээ','Services'],['projects.html','Төслүүд','Projects'],['news.html','Мэдээ мэдээлэл','News'],['contact.html','Холбоо барих','Contact']];
const pg=location.pathname.split('/').pop()||'index.html';
const nav=N.map(([h,m,e])=>{const a=`<a href="${h}"${h==pg||(h=='services.html'&&pg.startsWith('service'))?' aria-current="page"':''} data-en="${e}">${m}</a>`;return h=='services.html'?`<span class="dd">${a}<span class="sub">${S.map(s=>`<a href="service-${s[0]}.html" data-en="${s[2]}">${s[1]}</a>`).join('')}</span></span>`:a}).join('');
document.body.insertAdjacentHTML('afterbegin',`<header class="hd"><div class="w"><div class="top"><a class="br" href="index.html"><img src="images/logo.png" alt=""><span data-en="NUMAN-ALTAI LLC">НУМАН-АЛТАЙ ХХК</span></a><div class="tr"><form class="sr" action="https://www.google.com/search" target="_blank"><input type="hidden" name="as_sitesearch" value="numan.mn"><input name="q" aria-label="Search"><button aria-label="Search"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#1B4FD8" stroke-width="2.4"><circle cx="10" cy="10" r="6"/><path d="M15 15l6 6"/></svg></button></form><span class="lang"><button data-l="mn">MN</button><button data-l="en">EN</button></span></div></div><nav>${nav}</nav></div></header>`);
document.body.insertAdjacentHTML('beforeend',`<footer class="ft"><div class="w"><a class="br" href="index.html"><img src="images/logo.png" alt=""><span data-en="NUMAN-ALTAI LLC">НУМАН-АЛТАЙ ХХК</span></a><div class="fc"><h4 data-en="Contact information">Холбоо барих мэдээлэл</h4><p><span data-en="Phone:">Утас:</span> <a href="tel:+97677028199">+976 7702 8199</a><i>|</i><span data-en="Email:">И-мэйл:</span> <a href="mailto:info@numan.mn">info@numan.mn</a><i>|</i><span data-en="Address:">Хаяг:</span> <span data-en="Ulaanbaatar">Улаанбаатар хот</span></p></div><div class="fr"><div class="so"><a href="#" aria-label="Facebook"><svg viewBox="0 0 24 24"><path fill="currentColor" stroke="none" d="M14 8.5h2V5.5h-2.3C11.5 5.5 10 7 10 9.2V11H8v3h2v5.5h3V14h2.2l.5-3H13V9.4c0-.5.3-.9 1-.9z"/></svg></a><a href="#" aria-label="Instagram"><svg viewBox="0 0 24 24"><rect x="4" y="4" width="16" height="16" rx="5"/><circle cx="12" cy="12" r="3.6"/><circle cx="17" cy="7" r=".9" fill="currentColor" stroke="none"/></svg></a><a href="#" aria-label="YouTube"><svg viewBox="0 0 24 24"><rect x="3" y="6" width="18" height="12" rx="3.5"/><path fill="currentColor" stroke="none" d="M10.4 9.6v4.8l4.2-2.4z"/></svg></a></div><small>© 2026 <span data-en="Numan-Altai LLC">Нуман-Алтай ХХК</span> · www.numan.mn</small></div></div></footer>`);
document.querySelectorAll('.mq').forEach(m=>[...m.children].forEach(c=>{const d=c.cloneNode(true);d.classList.add('dup');d.tabIndex=-1;d.setAttribute('aria-hidden','true');m.append(d)}));
let L;try{L=new URLSearchParams(location.search).get('lang')||localStorage.l}catch(e){}
const E=[...document.querySelectorAll('[data-en]')],B=[...document.querySelectorAll('[data-l]')],Q=document.querySelector('.sr input');
E.forEach(e=>e.m=e.innerHTML);
function set(l){document.documentElement.lang=l;E.forEach(e=>e.innerHTML=l=='en'?e.dataset.en:e.m);B.forEach(b=>b.setAttribute('aria-pressed',b.dataset.l==l));Q.placeholder=l=='en'?'Search…':'Хайх…';try{localStorage.l=l}catch(e){}}
B.forEach(b=>b.onclick=()=>set(b.dataset.l));
set(L=='en'?'en':'mn');
